package:
  name: jpegoptim
  version: 1.5.6
  epoch: 0
  description: jpegoptim - utility to optimize/compress JPEG files
  copyright:
    - license: GPL-3.0

environment:
  contents:
    packages:
      - busybox
      - gcc
      - libjpeg-turbo-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tjko/jpegoptim
      tag: v${{package.version}}
      expected-commit: d0c79a8eb4cac61d1d4797ad93d8a49ffdb1ec29

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: tjko/jpegoptim
    strip-prefix: v

test:
  pipeline:
    - name: Run basic jpegoptim tests
      runs: |
        jpegoptim --version | grep v${{package.version}}
        jpegoptim --help
