package:
  name: php-8.2-zts-amqp
  version: "2.2.0"
  epoch: 0
  description: "PHP extension to communicate with any AMQP compliant server"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-${{vars.phpMM}}-zts
      - rabbitmq-c

var-transforms:
  - from: ${{package.name}}
    match: ^php-(\d+\.\d+)-zts-.*$
    replace: "$1"
    to: phpMM

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-${{vars.phpMM}}-zts
      - php-${{vars.phpMM}}-zts-dev
      - rabbitmq-c-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/php-amqp/php-amqp
      tag: "v${{package.version}}"
      expected-commit: aa233ad7b19a2ca14e1b13a16cb4b5720aa3ef6c

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: |
      set -x
      ./configure

  - uses: autoconf/make

  - name: Make install
    runs: |
      set -x
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=amqp.so" > "${{targets.subpkgdir}}/etc/php/conf.d/amqp.ini"

update:
  enabled: true
  github:
    identifier: php-amqp/php-amqp
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - uses: test/tw/ldd-check
