package:
  name: php-8.5-zts-pecl-mongodb
  version: "2.1.7"
  epoch: 0
  description: "PHP ${{vars.phpMM}} MongoDB driver - PECL"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - php-${{vars.phpMM}}-zts

var-transforms:
  - from: ${{package.name}}
    match: ^php-(\d+\.\d+)-zts-.*$
    replace: "$1"
    to: phpMM

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-${{vars.phpMM}}-zts-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: 3b50c0d471fcbc00e4e87b43f8d9ca138ea28e260c7983b6f8cc409308c5fe884a14be2dbc4449af35f3caf8cf570897d5c3dcfa0286cf06c5f19882e6818e77

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

test:
  environment:
    contents:
      packages:
        - php-${{vars.phpMM}}-zts
  pipeline:
    - name: Verify Extension is Loaded
      runs: |
        echo "<?php
        if (!extension_loaded('mongodb')) {
            die('The MongoDB PHP extension is not loaded. Please install or enable it.\n');
        }
        ?>" > test.php
        php test.php
        if [ $? -ne 0 ]; then
          echo "Test failed: Unable to use mongodb extension."
          exit 1
        else
          echo "Test passed: mongodb extension is functional."
        fi
    - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 11158
