name: 'Melange build'
description: 'Builds a package using melange'

inputs:
  package-file:
    description: 'The melange file to build'
    required: true
  signing-key-file:
    description: 'The signing key to use for signing the package'
    required: true
  arch:
    description: 'The architecture to build for'
    required: true
  commit-sha:
    description: 'The GitHub SHA of the commit'
    required: true
  cache-dir:
    description: 'The directory to use for caching apk files'
    required: false
    default: 'apk-cache'

runs:
  using: 'composite'
  steps:
    - name: Build package
      run: |
        packageName=${${{ inputs.package-file }}%.yaml}

        melange build \
          --apk-cache-dir ${{ inputs.cache-dir }} \
          --arch ${{ inputs.arch }} \
          --generate-index=false \
          -r https://packages.wolfi.dev/os \
          -k https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
          -r https://glimmer-labs.github.io/wolfi \
          -k https://glimmer-labs.github.io/wolfi/glimmer-labs-signing.rsa.pub \
          --signing-key ${{ inputs.signing-key-file }} \
          --git-repo-url=https://github.com/glimmer-labs/wolfi \
          --git-commit=${{ inputs.commit-sha }} \
          --pipeline-dir=./pipelines \
          --source-dir=./${packageName} \
          ${{ inputs.package-file }}
