package:
  name: php-8.5-sqlsrv
  version: "5.13.0"
  epoch: 100 # Start epoch at 100 to have higher priority than wolfi/os
  description: "Provides PHP ${{vars.phpMM}} Microsoft Drivers for SQL Server (SQLSRV)"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-${{vars.phpMM}}

var-transforms:
  - from: ${{package.name}}
    match: ^php-(\d+\.\d+)-.*$
    replace: "$1"
    to: phpMM

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc
      - libtool
      - php-${{vars.phpMM}}-dev
      - unixodbc-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/msphpsql
      tag: "v${{package.version}}"
      expected-commit: fd6d71d987dddcea413d9fc94234191cb82e4a28

  - runs: |
      cd source
      bash ./packagize.sh

  - working-directory: source/sqlsrv
    uses: pecl/phpize

  - working-directory: source/sqlsrv
    uses: autoconf/make

  - working-directory: source/sqlsrv
    uses: pecl/install
    with:
      extension: "sqlsrv"

  - uses: strip

update:
  enabled: true
  github:
    identifier: microsoft/msphpsql
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - uses: test/tw/ldd-check
