issuer: https://token.actions.githubusercontent.com
subject: repo:glimmer-labs/wolfi:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: glimmer-labs/wolfi/.github/workflows/melange-updater.yaml@refs/heads/main

permissions:
  issues: write
  contents: write
  workflows: write
  pull_requests: write