issuer: https://token.actions.githubusercontent.com
subject: repo:glimmer-labs/wolfi:pull_request
claim_pattern:
  job_workflow_ref: ^glimmer-labs/wolfi/.github/workflows/pr.yaml@refs/pull/[0-9]+/merge$

permissions:
  contents: write
